"""create all fitness tables

Revision ID: eedb5304886a
Revises: a69ad3ad4ff5
Create Date: 2025-12-08 16:37:51.366907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedb5304886a'
down_revision = 'a69ad3ad4ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BodyMeasurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('measure_date', sa.DateTime(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('BodyMeasurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_BodyMeasurements_measure_date'), ['measure_date'], unique=False)

    op.create_table('Exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body_part_id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=200), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['body_part_id'], ['BodyParts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'created_by', name='uix_name_creator')
    )
    op.create_table('WorkoutTemplates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PersonalRecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('pr_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint("pr_type IN ('max_weight', 'max_reps', 'max_volume')", name='ck_pr_type'),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', 'pr_type', name='uix_user_exercise_type')
    )
    op.create_table('TemplateDays',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['WorkoutTemplates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'day_number')
    )
    op.create_table('WorkoutSessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['WorkoutTemplates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SetLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('reps_actual', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.CheckConstraint("status IN ('completed', 'skipped', 'failed')", name='ck_status'),
    sa.CheckConstraint('rpe <= 10', name='ck_rpe_max'),
    sa.CheckConstraint('rpe >= 1', name='ck_rpe_min'),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['WorkoutSessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TemplateExercises',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(length=20), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('suggested_weight_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id', 'day_number'], ['TemplateDays.template_id', 'TemplateDays.day_number'], ),
    sa.ForeignKeyConstraint(['template_id'], ['WorkoutTemplates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'day_number', 'exercise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TemplateExercises')
    op.drop_table('SetLogs')
    op.drop_table('WorkoutSessions')
    op.drop_table('TemplateDays')
    op.drop_table('PersonalRecords')
    op.drop_table('WorkoutTemplates')
    op.drop_table('Exercises')
    with op.batch_alter_table('BodyMeasurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_BodyMeasurements_measure_date'))

    op.drop_table('BodyMeasurements')
    # ### end Alembic commands ###
